train:
    batch_size: 1024
    shuffle: true
    pin_memory: true
    num_workers: 4
    persistent_workers: true
valid:
    batch_size: 1024
    shuffle: false
    pin_memory: true
    num_workers: 4
    persistent_workers: true
test:
    batch_size: 1024
    shuffle: false
    pin_memory: true
    num_workers: 4
    persistent_workers: true
