distance_GraphTransformer_gdb13:
    encdec_hidden_dims:
        x: 256
        e: 128
        y: 128
        dist: 64

    transf_inout_dims:
        x: 256
        e: 64
        y: 64

    transf_ffn_dims:
        x: 256
        e: 128
        y: 256

    transf_hparams:
        heads: 8

    num_layers: 12
    use_residuals_inout: true
    simpler: true